"""add run_month to employees

Revision ID: c69f8c2d4085
Revises: b405324dd921
Create Date: 2026-01-23 01:12:35.497163
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = "c69f8c2d4085"
down_revision = 'b405324dd921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('run_month', sa.String(length=7), nullable=False))
    op.add_column('employees', sa.Column('working_hours', sa.Float(), nullable=False))
    op.alter_column('employees', 'department',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('email'), table_name='employees')
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_run_month'), 'employees', ['run_month'], unique=False)
    op.create_unique_constraint('uq_employee_run_month_email', 'employees', ['run_month', 'email'])
    op.drop_column('employees', 'created_at')
    op.drop_column('employees', 'simulate_failure')
    op.drop_column('employees', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('simulate_failure', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.drop_constraint('uq_employee_run_month_email', 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_run_month'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.create_index(op.f('email'), 'employees', ['email'], unique=True)
    op.alter_column('employees', 'department',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('employees', 'working_hours')
    op.drop_column('employees', 'run_month')
    # ### end Alembic commands ###
